version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-torrent-bot
    environment:
      - TELEGRAM_BOT_TOKEN=your_telegram_bot_token_here
      - TRANSMISSION_HOST=transmission
      - TRANSMISSION_PORT=9091
      - TRANSMISSION_USERNAME=transmission
      - TRANSMISSION_PASSWORD=transmission
      - DOWNLOAD_DIR=/games
    restart: unless-stopped